# Generated by Django 6.0.7 on 2026-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_latitude_order_longitude_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Triggers an automated inventory alert when stock falls to or below this quantity'),
        ),
    ]
