# Generated by Django 6.0.7 on 2026-09-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='LIMITED OFFER', max_length=60, verbose_name='Badge Pill Text')),
                ('text', models.TextField(default='Use code <strong>SAVE10</strong> for 10% off • Complimentary express shipping on orders over $100', help_text='The promotional text. Basic HTML like <strong> is allowed.', verbose_name='Announcement Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active (Show on site)')),
                ('background_gradient', models.CharField(blank=True, default='linear-gradient(90deg, #3730a3 0%, #4f46e5 50%, #7c3aed 100%)', max_length=255, verbose_name='Background CSS Gradient / Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top Announcement Bar',
                'verbose_name_plural': 'Top Announcement Bar',
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Feature Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Description / Subtitle')),
                ('icon', models.CharField(choices=[('truck', 'Truck / Delivery & Shipping'), ('shield', 'Shield / Official Warranty'), ('lock', 'Lock / Encrypted Checkout & SSL'), ('support', 'Concierge / 24/7 Live Support'), ('award', 'Award / Quality Guarantee'), ('refresh', 'Refresh / Easy 14-Day Returns'), ('star', 'Star / Premium Rating'), ('credit-card', 'Credit Card / Flexible Payment')], default='truck', max_length=40, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Trust Badge / Store Perk',
                'verbose_name_plural': 'Trust Badges / Store Perks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='FLAGSHIP COLLECTION 2026', max_length=100, verbose_name='Top Tag Pill')),
                ('title', models.CharField(default='Unrivaled Precision. <br><span class="logo-text-gradient">Pure Innovation.</span>', max_length=255, verbose_name='Main Headline (HTML allowed)')),
                ('description', models.TextField(default='Engineered for excellence. Explore our hand-curated catalog of advanced hardware, high-fidelity audio, and luxury lifestyle pieces.', verbose_name='Description Text')),
                ('product_badge_text', models.CharField(default='Verified 4.9 Rating • In Stock', max_length=120, verbose_name='Product Badge Subtitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='store.product', verbose_name='Featured Hero Product (Optional override)')),
            ],
            options={
                'verbose_name': 'Home Hero Banner & Showcase',
                'verbose_name_plural': 'Home Hero Banner & Showcase',
            },
        ),
    ]
