# Generated by Django 6.0.7 on 2026-09-06 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_siteannouncement_trustbadge_herobanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='', max_length=80)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='', verbose_name='Admin Answer')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Q&A',
                'verbose_name_plural': 'Product Q&A',
                'ordering': ['-created_at'],
            },
        ),
    ]
