# Generated by Django 6.0.7 on 2026-09-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_add_product_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_details',
            field=models.CharField(blank=True, default='', help_text='Chosen options e.g. Color: Black | Size: XL | Storage: 256GB', max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(blank=True, help_text='Hex color code e.g. #1e293b (for Color type)', max_length=30),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(choices=[('Color', 'Color Finish (اللون)'), ('Size', 'Clothing / Item Size (المقاس)'), ('Storage', 'Storage Capacity (السعة)'), ('RAM', 'RAM Memory (الرام)'), ('Option', 'Custom Option (مواصفة أخرى)')], default='Color', help_text='Variant type: Color, Size, Storage, RAM, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra price added to base price e.g. 100.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.CharField(help_text='Variant value e.g. Midnight Black, 256GB, XL', max_length=100),
        ),
    ]
